name: Deploy Prefect flow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      

    

      - name: Prefect Deploy
        env:
          
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          docker build -t demo-flow:v1 .
          docker run -d --env-file .env demo-flow:v1

